import React from "react";
import Head from "next/head";
import Layout, { s } from "../components/layout";

function staticPage(props: { users: Array<any> }) {
  const { users } = props;
  // console.log(users);

  const userStyles = {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
  };
  const mapStyles = {
    backgroundColor: "#f1f1f1",
    margin: "1em",
    padding: "1em",
    borderRadius: "0.5em",
    fontSize: "calc(0.25em + 0.5vw)",
    overflowX: "scroll",
    maxWidth: "80vw",
  };

  return (
    <Layout>
      <>
        <h1 className={s.title}>Static Props</h1>
        <Head>
          <title>Next JS | getStaticProps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>
          Getting data from{" "}
          <code className={s.code}>
            <a href="https://jsonplaceholder.typicode.com/users">
              {'"'}https://jsonplaceholder.typicode.com/users{'"'}
            </a>
          </code>
        </p>
        <div className={s.cardBox} style={userStyles as React.CSSProperties}>
          {users.map((user: any, index: number) => (
            <div key={index}>
              <pre style={mapStyles as React.CSSProperties}>
                {JSON.stringify(user, null, 4)}
              </pre>
            </div>
          ))}
        </div>
      </>
    </Layout>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const dataUsers = await res.json();
  return {
    props: {
      users: dataUsers,
    },
  };
}

export default staticPage;
